"""Layer 2 of spec section 15: every fixture against its committed descriptors.

Each page under ``tests/fixtures/extract/pages`` has a header comment saying
what it tests and a committed expected ``FieldDescriptor`` list under
``tests/fixtures/extract/expected``. This module asserts that the extractor
still produces exactly that, so any change to a selector, a signal, a group, or
an ordering shows up as a diff and has to be an intentional change with a
CHANGELOG note behind it.

**Bounding boxes are excluded from the comparison, and only bounding boxes.** A
box depends on the fonts the machine happens to have and the window the browser
happens to open, so committing one would be committing a flake. What the box is
*for* is ``is_visible``, and that is compared exactly: the honeypot fixture
passes or fails on whether the three invisible controls were excluded, which is
the part worth asserting.

The expectations are regenerated by ``scripts/refresh_fixtures.py``, which is a
deliberate act producing a diff to review, never a side effect of a test run.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from autofill_audit.descriptors import ExtractionResult, FieldDescriptor

pytestmark = pytest.mark.e2e

FIXTURES: tuple[str, ...] = (
    "canvas_only",
    "clean_labeled",
    "closed_shadow_root",
    "cross_origin_iframe",
    "duplicate_ids",
    "honeypot",
    "injected_field",
    "malformed_markup",
    "many_options",
    "mmyy_composite",
    "no_form_element",
    "open_shadow_root",
    "radio_checkbox_groups",
    "same_origin_iframe",
    "split_expiry_select_text",
    "split_expiry_two_selects",
    "unlabeled",
)
"""The thirteen fixtures spec section 15 layer 2 names, plus four.

The extra four are the cross-origin frame, which the P2 gate requires an outcome
for and which the thirteen do not name; the radio and checkbox groups, which
spec section 9.5 requires and which the generated corpus does not emit; and the
malformed markup page and the five thousand option select, which are the
extractor-scoped half of the malformed input list of spec section 15."""


def comparable(descriptor: FieldDescriptor) -> dict[str, Any]:
    """The descriptor as JSON, minus the one member that is not reproducible."""
    payload = descriptor.to_json()
    payload.pop("bbox")
    return payload


def snapshot(result: ExtractionResult) -> dict[str, Any]:
    """The whole extraction result, in the shape the expectation files hold."""
    return {
        "fields": [comparable(item) for item in result.fields],
        "honeypots": [comparable(item) for item in result.honeypots],
        "canvas_regions": [item.to_json() for item in result.canvas_regions],
        "warnings": [item.to_json() for item in result.warnings],
        "truncated": result.truncated,
        "frame_count": result.frame_count,
    }


@pytest.mark.parametrize("name", FIXTURES)
def test_fixture_matches_its_committed_descriptors(
    extract_page: Any, expected_dir: Path, name: str
) -> None:
    """The extracted result is exactly what was committed for this page."""
    result = extract_page(f"{name}.html")
    expected = json.loads((expected_dir / f"{name}.json").read_text(encoding="utf-8"))
    assert snapshot(result) == expected


@pytest.mark.parametrize("name", FIXTURES)
def test_every_fixture_says_what_it_tests(pages_dir: Path, name: str) -> None:
    """Spec section 15 requires a comment at the top of every fixture.

    Asserted mechanically, because a rule that lives only in prose is a rule the
    eighteenth fixture quietly breaks.
    """
    header = (pages_dir / f"{name}.html").read_text(encoding="utf-8").split("-->", 1)[0]
    assert "Tests:" in header, f"{name}.html: no header comment saying what it tests"
    assert "Not a copy of any live site" in header, f"{name}.html: no provenance statement"
