"""Behaviour of the commit-message check.

One blocked vendor name is reconstructed from its codepoints below rather than
written out, for the same reason the check stores its blocklist encoded: this
repository forbids those strings, and a test file is still a file.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import check_commit_msg

EM_DASH = chr(0x2014)
EN_DASH = chr(0x2013)
BLOCKED_VENDOR = bytes((0x63, 0x6C, 0x61, 0x75, 0x64, 0x65)).decode("ascii")


@pytest.mark.parametrize(
    "message",
    [
        "p0: repository foundations",
        "taxonomy: add the five extra labels\n\nSpec section 7.2 enumerates them.",
        "ci: cache the browser directory on the resolved playwright version",
        "docs: record the resolved toolchain in adr 0001",
    ],
)
def test_plain_engineering_messages_are_accepted(message: str) -> None:
    assert check_commit_msg.check_message(message) == []


def test_em_dash_is_rejected() -> None:
    reasons = check_commit_msg.check_message(f"p0: foundations {EM_DASH} first cut")
    assert len(reasons) == 1
    assert "U+2014" in reasons[0]


def test_en_dash_is_rejected() -> None:
    reasons = check_commit_msg.check_message(f"p0: phases 1{EN_DASH}3")
    assert len(reasons) == 1
    assert "U+2013" in reasons[0]


@pytest.mark.parametrize(
    "message",
    [
        "p0: foundations\n\nGenerated with a helpful tool",
        "p0: foundations\n\ngenerated by an ai",
        "p0: foundations\n\nwritten by an agent",
        "p0: foundations\n\nthis is ai-generated work",
        "p0: foundations\n\nCo-Authored-By: Someone <someone@example.invalid>",
        "p0: foundations\n\npaired with an ai assistant",
        "p0: foundations\n\nthanks to the assistant",
    ],
)
def test_attribution_artifacts_are_rejected(message: str) -> None:
    assert check_commit_msg.check_message(message) != []


def test_a_blocked_vendor_name_is_rejected() -> None:
    reasons = check_commit_msg.check_message(f"p0: foundations\n\nwith help from {BLOCKED_VENDOR}")
    assert len(reasons) == 1
    assert "vendor name" in reasons[0]


def test_git_comment_lines_are_ignored() -> None:
    message = (
        "p0: foundations\n"
        "# Please enter the commit message for your changes.\n"
        f"# an assistant wrote this comment with a {EM_DASH} in it\n"
    )
    assert check_commit_msg.check_message(message) == []


def test_everything_below_the_scissors_line_is_ignored() -> None:
    message = (
        "p0: foundations\n"
        "# ------------------------ >8 ------------------------\n"
        "diff --git a/x b/x\n"
        f"+an assistant {EM_DASH} wrote this\n"
    )
    assert check_commit_msg.check_message(message) == []


def test_message_body_strips_comments_and_scissors() -> None:
    body = check_commit_msg.message_body("subject\n#comment\nbody\n# --- >8 ---\ntrailing\n")
    assert body.splitlines() == ["subject", "body"]


def test_every_pattern_carries_a_description() -> None:
    assert len(check_commit_msg.ATTRIBUTION_PATTERNS) >= 8
    for _, description in check_commit_msg.ATTRIBUTION_PATTERNS:
        assert description.strip()


def test_main_accepts_a_clean_message_file(tmp_path: Path) -> None:
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text("p0: repository foundations\n", encoding="utf-8")
    assert check_commit_msg.main([str(path)]) == 0


def test_main_rejects_a_dirty_message_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text(f"p0: foundations {EM_DASH} first cut\n", encoding="utf-8")
    assert check_commit_msg.main([str(path)]) == 1
    assert "rejected" in capsys.readouterr().err


def test_main_needs_exactly_one_argument(capsys: pytest.CaptureFixture[str]) -> None:
    assert check_commit_msg.main([]) == 1
    assert "usage" in capsys.readouterr().err


def test_main_reports_an_unreadable_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert check_commit_msg.main([str(tmp_path / "absent")]) == 1
    assert "cannot read" in capsys.readouterr().err
