"""``corpus validate``: the checks that run over a corpus already on disk.

Generation asserts its own invariants while the form is still in memory
(spec section 8.1 step 8). This module checks the different question: that what
reached the disk is still coherent. The two are not the same check, and the
second one is the one that catches a hand-edited answer key, a partial write, a
corpus generated by an older generator, or a form file deleted by a stray clean.

Five checks, each of which can fail independently so that one failure does not
mask the rest:

1. Every answer key validates against the committed schema.
2. The manifest agrees with what is on disk: same form set, same shas.
3. Every selector in every key resolves to exactly one element in its form, for
   the controls that are in the static markup. Controls behind a shadow root or
   injected after load are checked against their host and their slot instead,
   which is as far as a static check can honestly go.
4. The split is disjoint, covers every form, and holds the locale rule.
5. Every label in the taxonomy is emitted by at least one key, which is law 2
   clause (b).
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from autofill_audit.corpus import domcheck
from autofill_audit.corpus.answer_key import validate_answer_key
from autofill_audit.corpus.manifest import label_coverage
from autofill_audit.corpus.selectors import SHADOW_SEPARATOR
from autofill_audit.corpus.split import HELD_OUT_LOCALE, PARTITIONS
from autofill_audit.corpus.tiers import Delivery

__all__ = ["ValidationReport", "load_keys", "validate_corpus"]


@dataclass(frozen=True, slots=True)
class ValidationReport:
    """The outcome of validating one corpus directory."""

    form_count: int
    field_count: int
    problems: tuple[str, ...]
    coverage: dict[str, int]

    @property
    def ok(self) -> bool:
        """True when nothing failed."""
        return not self.problems

    def missing_labels(self) -> list[str]:
        """Labels no answer key emitted."""
        return sorted(name for name, count in self.coverage.items() if count == 0)


def load_keys(root: Path) -> Iterator[tuple[str, dict[str, Any]]]:
    """Yield ``(form_id, document)`` for every answer key under ``root``."""
    keys_dir = root / "answer_keys"
    for path in sorted(keys_dir.glob("*.json")):
        yield path.stem, json.loads(path.read_text(encoding="utf-8"))


def _check_selectors(form_id: str, document: dict[str, Any], html: str) -> list[str]:
    """Check that every selector in one key resolves against its form."""
    problems: list[str] = []
    tree = domcheck.parse(html)
    for entry in document["fields"]:
        selector = entry["selector"]
        delivery = entry["provenance"]["delivery"]
        if delivery == Delivery.SHADOW.value:
            host = entry["provenance"]["shadow_host"]
            if host is None:
                problems.append(f"{form_id}: {selector} is shadow delivered with no host")
                continue
            if SHADOW_SEPARATOR not in selector:
                problems.append(f"{form_id}: {selector} is missing the shadow separator")
            found = domcheck.resolve(tree, f"#{host}")
            if len(found) != 1:
                problems.append(f"{form_id}: shadow host #{host} resolved to {len(found)} elements")
            continue
        if delivery == Delivery.INJECTED.value:
            slot = entry["provenance"]["injection_slot"]
            if slot is None:
                problems.append(f"{form_id}: {selector} is injected with no slot recorded")
                continue
            found = domcheck.resolve(tree, f"#{slot}")
            if len(found) != 1:
                problems.append(
                    f"{form_id}: injection slot #{slot} resolved to {len(found)} elements"
                )
            # The script assigns the bare id, not the selector, so the check
            # looks for the id the selector is built from. Comparing against the
            # selector text would look right and pass on nothing.
            injected_id = entry["provenance"]["element_id"]
            if injected_id is None or json.dumps(injected_id) not in html:
                problems.append(
                    f"{form_id}: the injection script never assigns the id behind {selector}"
                )
            continue
        try:
            found = domcheck.resolve(tree, selector)
        except ValueError as error:
            problems.append(f"{form_id}: {selector} is not a supported selector: {error}")
            continue
        if len(found) != 1:
            problems.append(
                f"{form_id}: {selector} resolved to {len(found)} elements, expected one"
            )
    return problems


def _check_manifest(root: Path, documents: dict[str, dict[str, Any]]) -> list[str]:
    """Check the manifest against what is actually on disk."""
    manifest_path = root / "manifest.json"
    if not manifest_path.is_file():
        return ["manifest.json is missing"]
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    problems: list[str] = []

    recorded = set(manifest["forms"])
    present = set(documents)
    for form_id in sorted(recorded - present):
        problems.append(f"{form_id}: in the manifest but has no answer key")
    for form_id in sorted(present - recorded):
        problems.append(f"{form_id}: has an answer key but is not in the manifest")

    for form_id in sorted(recorded & present):
        entry = manifest["forms"][form_id]
        html_path = root / "forms" / f"{form_id}.html"
        if not html_path.is_file():
            problems.append(f"{form_id}: the form file is missing")
            continue
        actual = hashlib.sha256(html_path.read_bytes()).hexdigest()
        if actual != entry["html_sha256"]:
            problems.append(f"{form_id}: the form file does not match its manifest sha")
        if entry["field_count"] != len(documents[form_id]["fields"]):
            problems.append(f"{form_id}: the manifest field count disagrees with its key")
    return problems


def _check_split(root: Path, documents: dict[str, dict[str, Any]]) -> list[str]:
    """Check split disjointness, coverage, and the held-out locale rule."""
    split_path = root / "split.json"
    if not split_path.is_file():
        return ["split.json is missing"]
    split = json.loads(split_path.read_text(encoding="utf-8"))
    problems: list[str] = []

    template_partitions: dict[str, str] = split["template_partitions"]
    form_partitions: dict[str, str] = split["form_partitions"]

    for name in set(form_partitions.values()) - set(PARTITIONS):
        problems.append(f"split.json uses the unknown partition {name!r}")

    missing = sorted(set(documents) - set(form_partitions))
    for form_id in missing:
        problems.append(f"{form_id}: has an answer key but no split assignment")

    # A template is an atom: every form of a template must land in the same
    # partition, apart from the held-out locale, which is lifted out of train.
    seen: dict[str, set[str]] = {}
    for form_id, partition in sorted(form_partitions.items()):
        document = documents.get(form_id)
        if document is None:
            problems.append(f"{form_id}: has a split assignment but no answer key")
            continue
        template_id = document["template_id"]
        locale = document["locale"]
        expected = template_partitions.get(template_id)
        if expected is None:
            problems.append(f"{template_id}: has no template partition")
            continue
        if locale == HELD_OUT_LOCALE and expected == "train":
            if partition != "excluded":
                problems.append(
                    f"{form_id}: the held-out locale on a training template must be "
                    f"excluded, found {partition!r}"
                )
        elif partition != expected:
            problems.append(
                f"{form_id}: partition {partition!r} disagrees with its template's {expected!r}"
            )
        if locale == HELD_OUT_LOCALE and partition == "train":
            problems.append(f"{form_id}: the held-out locale must not appear in train")
        seen.setdefault(template_id, set()).add(partition)

    for template_id, partitions in sorted(seen.items()):
        real = partitions - {"excluded"}
        if len(real) > 1:
            problems.append(f"{template_id}: appears in more than one partition: {sorted(real)}")
    return problems


def validate_corpus(root: Path) -> ValidationReport:
    """Run every check over a corpus directory and return one report."""
    problems: list[str] = []
    documents: dict[str, dict[str, Any]] = {}
    field_count = 0

    if not (root / "answer_keys").is_dir():
        return ValidationReport(0, 0, (f"{root}: no answer_keys directory",), {})

    for form_id, document in load_keys(root):
        schema_problems = validate_answer_key(document)
        if schema_problems:
            problems.extend(f"{form_id}: {problem}" for problem in schema_problems)
            continue
        documents[form_id] = document
        field_count += len(document["fields"])

        html_path = root / "forms" / f"{form_id}.html"
        if not html_path.is_file():
            problems.append(f"{form_id}: has an answer key but no form file")
            continue
        problems.extend(_check_selectors(form_id, document, html_path.read_text(encoding="utf-8")))

    problems.extend(_check_manifest(root, documents))
    problems.extend(_check_split(root, documents))

    coverage = label_coverage(list(documents.values()))
    missing = sorted(name for name, count in coverage.items() if count == 0)
    if missing:
        problems.append("law 2 clause (b): no answer key emits " + ", ".join(missing))

    return ValidationReport(
        form_count=len(documents),
        field_count=field_count,
        problems=tuple(problems),
        coverage=coverage,
    )
